blank_issues_enabled: false
contact_links:
  - name: 🚀 Feature Request
    url: https://github.com/enesozturk/react-native-hold-menu/discussions/categories/ideas
    about: Share ideas for new features
  - name: ❓ Ask a Question
    url: https://github.com/enesozturk/react-native-hold-menu/discussions/categories/q-a
    about: Ask the community for help